on:
  push:
    branches:
      - master
      - dev

name: Check reverse dependencies

jobs:
  revdep:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macos-latest, r: "release" }

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.config.os }}-${{ matrix.config.r }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ matrix.config.os }}-r-${{ matrix.config.r }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ matrix.config.os }}-r-${{ matrix.config.r }}-1-

      - name: Cache revdep packages
        uses: actions/cache@v1
        with:
          path: "revdep"
          key: ${{ matrix.config.os }}-r-${{ matrix.config.r }}-1-revdep-${{ hashFiles('revdep/checks/libraries.csv') }}
          restore-keys: ${{ matrix.config.os }}-r-${{ matrix.config.r }}-1-revdep-

      - name: Install dependencies
        env:
          OS_TYPE: ${{ runner.os }}
        run: Rscript ./.github/install_deps.R
        shell: bash

      - name: Install revdepcheck
        run: |
          if (!requireNamespace("revdepcheck", quietly = TRUE)) {
            options(repos = "https://cloud.r-project.org")
            remotes::install_github("r-lib/revdepcheck")
          }
        shell: Rscript {0}

      - name: Revdepcheck
        run: |
          options(repos = "https://cloud.r-project.org")
          revdepcheck::revdep_reset()
          revdepcheck::revdep_check(num_workers = 4L)
          revdepcheck::revdep_summary()
        shell: Rscript {0}

      # - name: Upload check results
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: ${{ runner.os }}-r${{ matrix.config.r }}-revdepresults
      #     path: revdep/
